# 数据库连接信息
db:
  host: 10.0.0.11
  database: demo
  user: demo
  password: b26ZMnAAZMjjsmMc
# 处理数量，'all' = 全部更新
num: all
# 替换词库
word:
  class: # 扩展分类
    - { "7-12岁": "少儿,儿童",
        "13-17岁": "少年",
        "18岁及以上": "成人",
        "Hong": "",
        "Kong": "",
        "ITV": "电视,卫视",
        "LOLI": "萝莉",
        "VIP尊享": "",
        "VIP集": "剧集,剧情",
        "VIP": "",
        "中国动漫": "国创",
        "中国台湾": "台湾",
        "中国大陆": "内地",
        "中国香港": "香港",
        "中国": "国创",
        "儿歌精选": "儿歌,精选",
        "儿童搞笑": "儿童,搞笑",
        "儿童教育": "儿童,教育",
        "其他动漫": "其他,动漫",
        "其他综艺": "其他,综艺",
        "其它": "其他",
        "内地剧场": "内地,剧情",
        "动态漫": "动态漫画",
        "动态漫画画": "动态漫画",
        "动漫电影": "动漫,电影",
        "动漫音乐": "动漫,音乐",
        "动画电影": "动画,动漫,电影",
        "医疗健康": "医疗,健康",
        "卡通动漫": "卡通,动漫",
        "卫视剧": "电视,卫视",
        "即兴喜剧": "即兴,喜剧",
        "历史人文": "历史,人文",
        "历史文化": "历史,文化",
        "历史革命": "历史,革命",
        "反腐扫黑": "反腐,扫黑",
        "台剧": "台湾,剧集",
        "台湾剧": "台湾,剧集",
        "合作活动": "合作,活动",
        "启蒙英语": "启蒙,英语,学习,幼教",
        "唱唱跳跳": "唱跳,舞蹈",
        "国产综艺": "内地,综艺",
        "国产动漫": "国创,动漫",
        "国产动画": "国创,动画",
        "国产剧": "内地",
        "国产": "内地",
        "国学精粹": "国学,精粹",
        "国家地理": "地理",
        "外语学习": "外语,学习",
        "大陆综艺": "内地,综艺",
        "天津卫视": "天津,卫视,电视",
        "太空宇宙": "太空,宇宙",
        "女孩爱看": "女孩",
        "娱乐节目": "娱乐,明星",
        "婚恋情感": "婚恋,情感",
        "学前教育": "早教,教育,学习,幼儿",
        "学英语": "学习,英语",
        "安徽卫视": "安徽,卫视,电视",
        "幼儿认知": "早教,教育,学习,幼儿",
        "幼小教育": "早教,教育,学习,幼儿",
        "幽默集锦": "幽默,集锦,搞笑",
        "强档热播": "热播,院线",
        "情感交友": "情感,交友",
        "情景喜剧": "情景,喜剧,搞笑",
        "情景喜": "情景,喜剧,搞笑",
        "手工绘画": "手工,绘画",
        "抗疫救灾": "抗疫,救灾",
        "搜狐视频大视野": "搜狐出品",
        "搞笑幽默": "搞笑,幽默",
        "播报-专访": "播报,专访",
        "播报-出品": "播报,出品",
        "播报-明星": "播报,明星,娱乐",
        "播报-独家": "播报,独家",
        "播报-现场": "播报,现场",
        "收藏鉴宝": "收藏,鉴宝",
        "文化艺术": "文化,艺术",
        "日常生活": "日常,生活",
        "日本动漫": "日本,番剧",
        "日本动画": "日本,番剧,动画",
        "日本综艺": "日本,综艺",
        "日漫": "日本,番剧",
        "早教益智": "早教,益智,教育,学习",
        "明星八卦": "明星,八卦,娱乐",
        "明星访谈": "明星,访谈",
        "极限运动": "极限,运动,体育",
        "棚内真人秀": "真人秀",
        "欧美剧": "欧美,剧集",
        "欧美动漫": "欧美,动漫",
        "欧美动画": "欧美,动画",
        "欧美综艺": "欧美,综艺",
        "武术散打": "武术,散打",
        "母婴护理": "母婴,护理",
        "民族音乐": "音乐,民族音乐",
        "流行音乐": "音乐,流行,流行音乐",
        "浙江卫视": "浙江,卫视,电视",
        "港剧": "香港,剧集",
        "港台动漫": "香港,台湾,动漫",
        "港台综艺": "香港,台湾,综艺",
        "港台": "香港,台湾",
        "港澳剧": "香港,澳门,剧集",
        "港澳": "香港,澳门",
        "游戏改编": "游戏改",
        "游戏竞技": "游戏,竞技",
        "演唱会": "音乐,演唱会",
        "漫画改编": "漫画改",
        "潮流文化": "潮流,文化,流行",
        "热门综艺": "热门,综艺",
        "父母课堂": "父母,学习,课堂,教育",
        "瑞士Switzerland": "瑞士",
        "Switzerland": "瑞士",
        "生活娱乐": "生活,娱乐",
        "生活技巧": "生活,技巧",
        "生活服务": "生活,服务",
        "生活消费": "生活,消费",
        "生活百科": "生活,百科",
        "电视剧": "剧集",
        "电音": "电音,音乐",
        "男孩爱看": "男孩",
        "相声小品": "相声,小品",
        "真人特摄": "真人,特摄",
        "社会题材": "社会",
        "竖短片": "竖屏,短片",
        "竖短": "竖屏,短片",
        "童话绘本": "童话,绘本",
        "篮球": "篮球,体育,运动",
        "精选短": "精选,短片",
        "纪录片": "记录",
        "绘画手工": "绘画,手工",
        "网络剧": "网络,剧集,网剧",
        "网络游戏": "网络,游戏",
        "网络电影": "网络,电影",
        "罪案": "犯罪,凶案,罪案",
        "美少女": "美女,少女,美少女",
        "美食教学": "美食,教学",
        "美食文化": "美食,文化",
        "美食旅游": "美食,旅游",
        "职业技能": "职业,技能",
        "自制节目": "自制",
        "自然科学": "自然,科学",
        "西班牙SPain": "西班牙",
        "记录片": "记录",
        "语言表达": "语言,表达",
        "课堂知识": "课堂,知识,学习",
        "超级网剧": "网络,剧集,网剧",
        "轻小说改编": "轻小说,小说改",
        "韩国动漫": "韩国,动漫",
        "韩国动画": "韩国,动画",
        "韩国综艺": "韩国,综艺",
        "音乐亚洲": "音乐,亚洲",
        "音乐剧": "音乐,剧集",
        "预告&amp;剧八卦": "预告,剧集,八卦" }
  area: # 地区
    - { "，": "",
        "(": "",
        ")": "",
        "/": ",",
        " ": "",
        ":中国大陆": "内地",
        "马来西亚Malaysia": "马来西亚",
        "馬來西亞Malay": "马来西亚",
        "马拉西亚": "马来西亚",
        "马来西": "马来西亚",
        "马来西亚亚": "马来西亚",
        "超级飞侠每一集飞往世界各地不同的城市或地": "其他",
        "电视剧以改革初期陕北地区的城乡生活为时空": "其他",
        "《果味香村》以黄桃、蜜瓜、刺梨、苹果、蜜": "其他",
        "在西南地区的一个刚刚脱贫的小村落——高石": "其他",
        "《我是冒险王》是青海卫视的一档探险栏目": "其他",
        "大型活动《芒果新童星》关注贫困地区儿童": "其他",
        "以日本东北地区和东京为舞台描写了命运悲": "其他",
        "刘昴星（小当家）是史上最年轻的通过中国": "日本",
        "记录了7个少数民族的当下生活体现的是少": "其他",
        "《坐庄2操盘手》是王珈执导的悬疑犯罪片": "其他",
        "清朝道光年间皇家御用烧锅“同盛金”埋藏": "其他",
        "适逢改革开放40周年美国格律文化传媒集": "其他",
        "以六盘山为切入点用鲜活的故事充分展示": "其他",
        "《不老乡音第二季》穿行湘西大地用镜头": "其他",
        "7月瓜果飘香是大力开展农产品销售和迎": "其他",
        "北京电影制片厂年出品": "北京",
        "蘇聯": "苏联",
        "菲律宾Philippines": "菲律宾",
        "荷兰Netherlands": "荷兰",
        "芬兰Finland": "芬兰",
        "美國USA": "美国",
        "美国南非加拿大": "美国,南非,加拿大",
        "美国、英国、德国": "美国,英国,德国",
        "瑞士Switzerland": "瑞士",
        "瑞典Sweden": "瑞典",
        "澳大利亚Australia": "澳大利亚",
        "港台": "香港,台湾",
        "泰國": "泰国",
        "法国德国日本": "法国,德国,日本",
        "沙特阿拉伯SaudiAra": "沙特阿拉伯",
        "比利时Belgium": "比利时",
        "比利": "比利时",
        "比利时时": "比利时",
        "英语": "其他",
        "皆可": "其他",
        "波黑": "波斯尼亚,黑塞哥维那",
        "欧美地区": "欧美",
        "欧美其他": "欧美,其他",
        "未知": "其他",
        "智利Chile": "智利",
        "日韩地区": "日本,韩国",
        "日韩": "日本,韩国",
        "日本日本剧": "日本",
        "新马": "新加坡,马来西亚",
        "新加坡美国": "新加坡,美国",
        "新加坡Singapore": "新加坡",
        "摩纳": "摩纳哥",
        "摩纳哥哥": "摩纳哥",
        "捷克斯洛伐克Czechoslovaki": "捷克斯洛伐克",
        "捷克美国": "捷克,美国",
        "德國": "德国",
        "德语": "德国",
        "意大": "意大利",
        "意大利利": "意大利",
        "巴勒斯坦被占领区": "巴勒斯坦",
        "委内瑞拉Venezuela": "委内瑞拉",
        "国外": "其他",
        "塞尔维": "塞尔维亚",
        "塞尔维亚亚": "塞尔维亚",
        "埃塞俄比亚Ethi": "埃塞俄比亚",
        "土耳其Turkey": "土耳其",
        "Turkey": "土耳其",
        "土耳": "土耳其",
        "土耳其其": "土耳其",
        "哈萨克斯": "哈萨克斯坦",
        "哈萨克斯坦坦": "哈萨克斯坦",
        "台灣Taiwan": "台湾",
        "古巴Cuba": "古巴",
        "叙利亚Syria": "叙利亚",
        "印度Indian": "印度",
        "印度India": "印度",
        "India": "印度",
        "印尼Indonesia": "印尼",
        "北京": "内地",
        "匈牙利Hungary": "匈牙利",
        "动漫": "日本",
        "加拿大Canada": "加拿大",
        "利比": "利比里亚",
        "利比里亚里亚": "利比里亚",
        "其它": "其他",
        "俄罗斯哈萨克斯坦": "俄罗斯,哈萨克斯坦",
        "俄罗斯Russia": "俄罗斯",
        "俄国Russia": "俄国",
        "中国香港": "香港",
        "中国香": "香港",
        "中国澳门": "澳门",
        "中国大陆法国": "内地,法国",
        "中国大陆": "内地",
        "中国内地": "内地",
        "中国大": "内地",
        "中国台湾": "台湾",
        "不详": "其他",
        "中国": "内地",
        "大陆": "内地",
        "USA": "美国",
        "UK": "英国",
        "U.S.A": "美国",
        "SouthAfrica": "南非",
        "NZ": "荷兰",
        "Mexico": "墨西哥",
        "Germany": "德国",
        "Denmark": "丹麦",
        "Canada加拿大": "加拿大",
        "Canada": "加拿大",
        "Australia": "澳大利亚",
        "Switzerland": "瑞士" }
  lang: # 语言
    - { "/": ",",
        " ": "",
        "55": "",
        ":汉语普通话": "普通话",
        ":韩语": "韩语",
        "马拉地语Marat": "马拉地语",
        "马来西亚": "马来语",
        "马来西": "马来语",
        "马来": "马来语",
        "音乐": "",
        "丹麦语Danish": "丹麦语",
        "丹麦语D": "丹麦语",
        "丹麦": "丹麦语",
        "乌克兰语Ukari": "乌克兰语",
        "乌克兰": "乌克兰语",
        "乌尔都": "乌尔都语",
        "俄罗斯语Russi": "俄语",
        "俄罗斯语": "俄语",
        "俄罗斯": "俄语",
        "俄语Russian": "俄语",
        "俄语Russina": "俄语",
        "俄語": "俄语",
        "克丘亚": "克丘亚语",
        "兰州": "",
        "其它": "其他",
        "冰岛语Icelan": "冰岛语",
        "比印度语Hindi": "印地语",
        "北印度语Hindi": "印地语",
        "北印度语": "印地语",
        "印度语Hindi": "印地语",
        "印度语": "印地语",
        "印地语Hindi": "印地语",
        "印地语h": "印地语",
        "印地": "印地语",
        "印度India": "印地语",
        "印度尼西亚语": "印尼语",
        "印度尼西亚": "印尼语",
        "印尼语Indone": "印尼语",
        "印度": "印地语",
        "南非語": "南非语",
        "四川方言": "四川话",
        "泰国语": "泰语",
        "泰国": "泰语",
        "泰語": "泰语",
        "泰米尔语Tamil": "泰米尔语",
        "土耳其语Turke": "土耳其语",
        "土耳其语Turki": "土耳其语",
        "土尔其语": "土耳其语",
        "土耳其": "土耳其语",
        "塞尔维亚克罗地亚语": "塞尔维亚语,克罗地亚语",
        "塞尔维亚－克罗地亚语": "塞尔维亚语,克罗地亚语",
        "塞尔维亚-": "塞尔维亚语",
        "塞尔维亚": "塞尔维亚语",
        "暂无": "其他",
        "未知": "其他",
        "国产": "普通话",
        "国语大陆": "普通话",
        "国语": "普通话",
        "中国大陆": "普通话",
        "中国大": "普通话",
        "中国香港": "粤语",
        "中国香": "粤语",
        "中国台湾": "闽南语",
        "台湾": "闽南语",
        "台语": "闽南语",
        "中国": "普通话",
        "中文": "普通话",
        "湖南方言": "湖南话,方言",
        "闽南方言": "闽南语,方言",
        "云南方言": "云南语,方言",
        "云南语": "云南语,方言",
        "闽南话": "闽南语",
        "上海": "上海话,方言",
        "南京": "南京话,方言",
        "北京": "北京话,方言",
        "四川": "四川话,方言",
        "山东": "山东话,方言",
        "客家": "客家话,方言",
        "徐州": "徐州话,方言",
        "武汉": "武汉话,方言",
        "河南": "河南话,方言",
        "福建": "福建话,方言",
        "胶辽": "胶辽话,方言",
        "重庆": "重庆话,方言",
        "陕西": "陕西话,方言",
        "闽南": "闽南语",
        "吴越": "吴语,方言",
        "维吾": "维语",
        "太湖": "",
        "河南越调": "越剧",
        "汉语普通话Mand": "普通话",
        "汉语普通话": "普通话",
        "汉语普通": "普通话",
        "汉语普": "普通话",
        "汉语方言及普通话": "普通话,方言",
        "汉语方言": "普通话,方言",
        "汉语四川话": "普通话,四川话,方言",
        "汉语": "普通话",
        "方言越调": "越剧",
        "方言话": "方言",
        "佛兰德斯语": "荷兰语",
        "佛兰德语": "荷兰语",
        "南非荷兰语": "南非语",
        "南非": "南非语",
        "加泰罗尼亚": "加泰罗尼亚语",
        "加泰罗": "加泰罗尼亚语",
        "加泰罗尼亚语尼亚语": "加泰罗尼亚语",
        "加拿大": "英语",
        "古希腊": "希腊语",
        "塔伽洛": "塔伽洛语",
        "墨西哥": "西班牙语",
        "西班牙": "西班牙语",
        "奥地利": "德语",
        "巴西": "葡萄牙语",
        "希伯来语Hebre": "希伯来语",
        "希伯来": "希伯来语",
        "库尔德": "库尔德语",
        "德国": "德语",
        "德語": "德语",
        "意大利": "意大利语",
        "意大": "意大利语",
        "意大利语利语": "意大利语",
        "挪威语Norweg": "挪威语",
        "挪威": "挪威语",
        "捷克斯洛伐克": "捷克语",
        "捷克语Czech": "捷克语",
        "捷克": "捷克语",
        "斯洛文尼亚": "斯洛文尼亚语",
        "无声": "默片",
        "无对白": "默片",
        "日本": "日语",
        "日語": "日语",
        "智利": "西班牙语",
        "朝鲜": "朝鲜语",
        "法国": "法语",
        "波兰语Polish": "波兰语",
        "波利尼西亚": "波利尼西亚语",
        "波斯语Persia": "波斯语",
        "波斯": "波斯语",
        "波黑": "波斯尼亚语",
        "波斯语尼亚语": "波斯尼亚语",
        "泰卢固语Te": "泰卢固语",
        "泰卢固": "泰卢固语",
        "斯洛伐": "斯洛伐克语",
        "斯洛伐克语克语": "斯洛伐克语",
        "比利时": "法语",
        "澳大利亚": "英语",
        "爱尔兰盖尔": "爱尔兰语",
        "爱沙尼亚": "爱沙尼亚语",
        "瑞典语Swedis": "瑞典语",
        "瑞典语S": "瑞典语",
        "瑞典": "瑞典语",
        "瑞士德语Swiss-": "德语",
        "瑞士德语": "德语",
        "瑞士语言": "德语",
        "瑞士语": "德语",
        "瑞士": "德语",
        "粵語": "粤语",
        "罗马尼亚语Roma": "罗马尼亚语",
        "罗马尼": "罗马尼亚语",
        "罗马尼亚语亚语": "罗马尼亚语",
        "美国手语": "英语,手语",
        "美国": "英语",
        "芬兰语Finnis": "芬兰语",
        "芬兰": "芬兰语",
        "艾马拉": "马拉语",
        "苏格兰盖尔": "苏格兰盖尔语",
        "苏联": "俄语",
        "英語英语": "英语",
        "英语英语": "英语",
        "英国": "英语",
        "荷兰语Dutch": "荷兰语",
        "荷蘭語": "荷兰语",
        "荷兰": "荷兰语",
        "菲律宾语Filip": "菲律宾语",
        "菲律宾塔加": "菲律宾语",
        "菲律宾": "菲律宾语",
        "葡萄牙语Portu": "葡萄牙语",
        "葡萄牙": "葡萄牙语",
        "蒙古语": "蒙语",
        "蒙古": "蒙语",
        "越南语Vietna": "越南语",
        "越南": "越南语",
        "越语": "越南语",
        "赣语Gan": "赣语",
        "西西里": "西西里语",
        "高棉": "高棉语",
        "普听话": "普通话",
        "阿姆哈": "阿姆哈拉语",
        "阿姆哈拉语拉语": "阿姆哈拉语",
        "阿拉伯": "阿拉伯语",
        "阿拉": "阿拉伯语",
        "阿拉伯语伯语": "阿拉伯语",
        "阿布": "其他",
        "韩国": "韩语",
        "马拉地语‎": "马拉地语",
        "Afrikaans": "荷兰语",
        "Athap": "其他",
        "Cantonese": "粤语",
        "Danish": "丹麦语",
        "Dari": "达里语",
        "English": "英语",
        "French": "法语",
        "Galic": "加利奇语",
        "German": "德语",
        "Hindi": "印地语",
        "India": "印地语",
        "Icelandic": "冰岛语",
        "Luxembourg": "卢森堡语",
        "Malayalam": "马拉雅拉姆语",
        "Pasht": "其他",
        "Persian": "波斯语",
        "Russian": "俄语",
        "Silent": "默片",
        "Swahi": "斯瓦希里语",
        "SwissGerm": "瑞士语",
        "Tamil": "泰米尔语",
        "Telugu": "泰卢固语",
        "Telu": "泰卢固语",
        "Turkish": "土耳其语",
        "Ukrai": "乌克兰语",
        "Welsh": "威尔士语",
        "Zulu": "祖鲁语",
        "spanish": "西班牙语",
        "话话": "话",
        "语语": "语" }